describe("general utils tests", function()
  local general = require("pwarp.util.general")
  describe("does_path_exist", function()
    it("when path exists, should return true", function()
      local result = general.does_path_exist("/home")
      assert.are_equal(true, result)
    end)

    it("when path does not exist, should return false", function()
      local result = general.does_path_exist("/jfajfaifs")
      assert.are_equal(false, result)
    end)
  end)

  describe("check_types", function()
    it("when types are valid, should return nothing", function()
      local success = pcall(function()
        general.check_types({ [""] = "string", [1] = "number" })
      end)
      assert.are_equal(true, success)
    end)

    it("when types are invalid, should throw error", function()
      local success = pcall(function()
        general.check_types({ [""] = "boolean" })
      end)
      assert.are_equal(false, success)
    end)
  end)
end)
