local config = require("pwarp.config")
local pwarp = require("pwarp")

describe("pwarp", function()
  describe("setup", function()
    it("when opts are nil, should not throw error and not setup", function()
      pwarp.setup()
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts are {}, should not throw error and not setup", function()
      pwarp.setup({})
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts are {enabled = false}, should not throw error and not setup", function()
      pwarp.setup({ enabled = false })
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts are {enabled = true}, should not throw error and not setup", function()
      pwarp.setup({})
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts have projects, should setup the projects in state", function()
      pwarp.setup({ projects = { { name = "test", path = "/home" } } })
      local projects = config.get_projects()
      assert.are_equal(1, #projects)
    end)
    it("when opts have projects,but is malformed, should throw error", function()
      local success = pcall(function()
        pwarp.setup({ projects = { { path = "/home" } } })
      end)
      assert.are_equal(false, success)
    end)
    it("when opts have projects,but path is malformed, should throw error", function()
      local success = pcall(function()
        pwarp.setup({ projects = { { name = "test", path = "fafs" } } })
      end)
      assert.are_equal(false, success)
    end)
    it("when opts have projects,but path is malformed, should throw error", function()
      local success = pcall(function()
        pwarp.setup({ projects = { { name = "test", path = "/home" } } })
      end)
      pwarp.list()
      assert.are_equal(false, success)
    end)
    -- TODO: continue testing (will need telescope for testing)
  end)
end)
