local config = require("pwarp.config")
local pwarp = require("pwarp")
local stub  = require("luassert.stub")

describe("pwarp", function()
  describe("setup", function()
    it("when opts are nil, should not throw error and not setup", function()
      pwarp.setup()
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts are {}, should not throw error and not setup", function()
      pwarp.setup({})
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts are {enabled = false}, should not throw error and not setup", function()
      pwarp.setup({ enabled = false })
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts are {enabled = true}, should not throw error and not setup", function()
      pwarp.setup({})
      local projects = config.get_projects()
      assert.are_equal(0, #projects)
    end)
    it("when opts have projects, should setup the projects in state", function()
      pwarp.setup({ projects = { { name = "test", path = "/home" } } })
      local projects = config.get_projects()
      assert.are_equal(1, #projects)
    end)
    it("when opts have projects,but is malformed, should throw error", function()
      local success = pcall(function()
        pwarp.setup({ projects = { { path = "/home" } } })
      end)
      assert.are_equal(false, success)
    end)
    it("when opts have projects,but path is malformed, should throw error", function()
      local success = pcall(function()
        pwarp.setup({ projects = { { name = "test", path = "fafs" } } })
      end)
      assert.are_equal(false, success)
    end)
  end)
  describe("goto", function()
    it("when goto is not a valid project, should print without throw", function()
      stub(vim,"cmd")

      local success = pcall(function()
        pwarp.setup({ projects = { { name = "test", path = "/home" } } })
      end)
      pwarp.goto("not-test")

      local buff_count = #vim.api.nvim_list_bufs()
      assert.are_equal(true, success)
      assert.are_equal(1,buff_count) -- take into account the test buffer
      assert.stub(vim.cmd).called(0)
    end)
    it("when goto is a valid project, should print without throw", function()
      stub(vim,"cmd")

      local success = pcall(function()
        pwarp.setup({ projects = { { name = "test", path = "/home" } } })
      end)
      pwarp.goto("test")

      local buff_count = #vim.api.nvim_list_bufs()
      assert.are_equal(true, success)
      assert.are_equal(1,buff_count) -- take into account the test buffer
      assert.stub(vim.cmd).called(1)
      assert.stub(vim.cmd).was_called_with("cd /home")
    end)
  end)
end)
